package com.csgo.dao;

import com.csgo.po.admin;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component("adminDao")
public interface adminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jun 21 16:29:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jun 21 16:29:22 CST 2020
     */
    int insert(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jun 21 16:29:22 CST 2020
     */
    int insertSelective(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jun 21 16:29:22 CST 2020
     */
    admin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jun 21 16:29:22 CST 2020
     */
    int updateByPrimaryKeySelective(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun Jun 21 16:29:22 CST 2020
     */
    int updateByPrimaryKey(admin record);

    /**
     * 管理员查询
     */
    List<admin> queryAdminInfoAll(admin admin);


    /**
     * 根据用户名和密码查询用户信息
     */
    admin queryUserByNameAndPassword(@Param("username") String username,@Param("password")  String password);
}