package com.csgo.dao;

import com.csgo.po.moneycharge;

public interface moneychargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moenycharge
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    int deleteByPrimaryKey(String chargeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moenycharge
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    int insert(moneycharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moenycharge
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    int insertSelective(moneycharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moenycharge
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    moneycharge selectByPrimaryKey(String chargeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moenycharge
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    int updateByPrimaryKeySelective(moneycharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moenycharge
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    int updateByPrimaryKey(moneycharge record);
}