package com.csgo.dao;

import com.csgo.po.notice;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component("noticeDao")
public interface noticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    int insert(notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    int insertSelective(notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    notice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    int updateByPrimaryKeySelective(notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    int updateByPrimaryKey(notice record);


    /**
     * 查询公告信息
     */
    List<notice> queryNoticeAll(@Param("content") String content);

    /**
     * 删除公告
     */
     void deleteNoticeByIds(List<Integer> id);



}