package com.csgo.dao;

import com.csgo.po.admin;
import com.csgo.po.user;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue May 25 22:32:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue May 25 22:32:49 CST 2021
     */
    int insert(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue May 25 22:32:49 CST 2021
     */
    int insertSelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue May 25 22:32:49 CST 2021
     */
    user selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue May 25 22:32:49 CST 2021
     */
    int updateByPrimaryKeySelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue May 25 22:32:49 CST 2021
     */
    int updateByPrimaryKey(user record);

    List<user> queryUserInfoAll(user user);

    user queryUserByNameAndPassword(@Param("username") String username, @Param("password")  String password);
}