package com.csgo.dao;

import com.csgo.po.Weapontype;
import com.csgo.po.weaponfeature;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface weaponfeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponfeature
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    int deleteByPrimaryKey(Integer weaponfeatureid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponfeature
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    int insert(weaponfeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponfeature
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    int insertSelective(weaponfeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponfeature
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    weaponfeature selectByPrimaryKey(Integer weaponfeatureid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponfeature
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    int updateByPrimaryKeySelective(weaponfeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponfeature
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    int updateByPrimaryKey(weaponfeature record);


    List<weaponfeature> queryFeatureInfoAll(weaponfeature weaponfeature);
}