package com.csgo.dao;

import com.csgo.po.Weapontype;
import com.csgo.po.admin;
import com.csgo.po.weapon;

import java.util.List;

public interface weaponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weapon
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    int deleteByPrimaryKey(Integer weaponid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weapon
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    int insert(weapon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weapon
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    int insertSelective(weapon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weapon
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    weapon selectByPrimaryKey(Integer weaponid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weapon
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    int updateByPrimaryKeySelective(weapon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weapon
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    int updateByPrimaryKey(weapon record);

    List<weapon> queryWeaponInfoAll(weapon weapon);

    List<weapon> getWeaponCountByType();
}