package com.csgo.dao;

import com.csgo.po.weaponquality;

public interface weaponqualityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponquality
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    int deleteByPrimaryKey(Integer weaponqualityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponquality
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    int insert(weaponquality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponquality
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    int insertSelective(weaponquality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponquality
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    weaponquality selectByPrimaryKey(Integer weaponqualityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponquality
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    int updateByPrimaryKeySelective(weaponquality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weaponquality
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    int updateByPrimaryKey(weaponquality record);
}