package com.csgo.po;

import java.io.Serializable;
import java.util.Date;

public class deal implements Serializable {


    private weaponfeature weaponfeature;
    private weaponquality weaponquality;
    private user user;
    private weapon weapon;

    public com.csgo.po.weapon getWeapon() {
        return weapon;
    }

    public void setWeapon(com.csgo.po.weapon weapon) {
        this.weapon = weapon;
    }

    public com.csgo.po.weaponfeature getWeaponfeature() {
        return weaponfeature;
    }

    public void setWeaponfeature(com.csgo.po.weaponfeature weaponfeature) {
        this.weaponfeature = weaponfeature;
    }

    public com.csgo.po.weaponquality getWeaponquality() {
        return weaponquality;
    }

    public void setWeaponquality(com.csgo.po.weaponquality weaponquality) {
        this.weaponquality = weaponquality;
    }

    public com.csgo.po.user getUser() {
        return user;
    }

    public void setUser(com.csgo.po.user user) {
        this.user = user;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.id
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.weaponid
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    private Integer weaponid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.total
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    private Float total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.userid
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.createdate
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.ispay
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    private Byte ispay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deal
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.id
     *
     * @return the value of deal.id
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.id
     *
     * @param id the value for deal.id
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.weaponid
     *
     * @return the value of deal.weaponid
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public Integer getWeaponid() {
        return weaponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.weaponid
     *
     * @param weaponid the value for deal.weaponid
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public void setWeaponid(Integer weaponid) {
        this.weaponid = weaponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.total
     *
     * @return the value of deal.total
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.total
     *
     * @param total the value for deal.total
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.userid
     *
     * @return the value of deal.userid
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.userid
     *
     * @param userid the value for deal.userid
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.createdate
     *
     * @return the value of deal.createdate
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.createdate
     *
     * @param createdate the value for deal.createdate
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.ispay
     *
     * @return the value of deal.ispay
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public Byte getIspay() {
        return ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.ispay
     *
     * @param ispay the value for deal.ispay
     *
     * @mbggenerated Tue Jun 01 21:18:15 CST 2021
     */
    public void setIspay(Byte ispay) {
        this.ispay = ispay;
    }
}