package com.csgo.po;

import java.io.Serializable;

public class moneycharge implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moenycharge.chargeid
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    private String chargeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moenycharge.money
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moenycharge.ischecked
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    private Integer ischecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moenycharge
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moenycharge.chargeid
     *
     * @return the value of moenycharge.chargeid
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    public String getChargeid() {
        return chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moenycharge.chargeid
     *
     * @param chargeid the value for moenycharge.chargeid
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    public void setChargeid(String chargeid) {
        this.chargeid = chargeid == null ? null : chargeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moenycharge.money
     *
     * @return the value of moenycharge.money
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moenycharge.money
     *
     * @param money the value for moenycharge.money
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moenycharge.ischecked
     *
     * @return the value of moenycharge.ischecked
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    public Integer getIschecked() {
        return ischecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moenycharge.ischecked
     *
     * @param ischecked the value for moenycharge.ischecked
     *
     * @mbggenerated Fri Jun 04 09:57:58 CST 2021
     */
    public void setIschecked(Integer ischecked) {
        this.ischecked = ischecked;
    }
}