package com.csgo.po;

import java.io.Serializable;
import java.util.Date;

public class notice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.createDate
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.author
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    private Integer author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.content
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notice
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.createDate
     *
     * @return the value of notice.createDate
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.createDate
     *
     * @param createdate the value for notice.createDate
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.author
     *
     * @return the value of notice.author
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.author
     *
     * @param author the value for notice.author
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.content
     *
     * @return the value of notice.content
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.content
     *
     * @param content the value for notice.content
     *
     * @mbggenerated Sat May 22 22:22:21 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}