package com.csgo.po;

import java.io.Serializable;

public class weaponquality implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weaponquality.WeaponQualityId
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    private Integer weaponqualityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weaponquality.WeaponQualityName
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    private String weaponqualityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weaponquality
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weaponquality.WeaponQualityId
     *
     * @return the value of weaponquality.WeaponQualityId
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    public Integer getWeaponqualityid() {
        return weaponqualityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weaponquality.WeaponQualityId
     *
     * @param weaponqualityid the value for weaponquality.WeaponQualityId
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    public void setWeaponqualityid(Integer weaponqualityid) {
        this.weaponqualityid = weaponqualityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weaponquality.WeaponQualityName
     *
     * @return the value of weaponquality.WeaponQualityName
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    public String getWeaponqualityname() {
        return weaponqualityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weaponquality.WeaponQualityName
     *
     * @param weaponqualityname the value for weaponquality.WeaponQualityName
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    public void setWeaponqualityname(String weaponqualityname) {
        this.weaponqualityname = weaponqualityname == null ? null : weaponqualityname.trim();
    }
}