package com.csgo.po;

import java.io.Serializable;

public class weapon implements Serializable {

   public weaponfeature weaponfeature;
   public weaponquality weaponquality;
   public Weapontype  weapontype;

    public com.csgo.po.weaponfeature getWeaponfeature() {
        return weaponfeature;
    }

    public void setWeaponfeature(com.csgo.po.weaponfeature weaponfeature) {
        this.weaponfeature = weaponfeature;
    }

    public com.csgo.po.weaponquality getWeaponquality() {
        return weaponquality;
    }

    public void setWeaponquality(com.csgo.po.weaponquality weaponquality) {
        this.weaponquality = weaponquality;
    }

    public com.csgo.po.Weapontype  getWeapontype() {
        return weapontype;
    }

    public void setWeapontype(Weapontype weapontype) {
        this.weapontype = weapontype;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weapon.WeaponId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    private Integer weaponid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weapon.WeaponName
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    private String weaponname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weapon.WeaponPrice
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    private Double weaponprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weapon.WeaponStore
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    private Integer weaponstore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weapon.WeaponFeatureId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    private Integer weaponfeatureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weapon.WeaponQualityId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    private Integer weaponqualityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weapon.WeaponTypeId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    private Integer weapontypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weapon
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weapon.WeaponId
     *
     * @return the value of weapon.WeaponId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public Integer getWeaponid() {
        return weaponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weapon.WeaponId
     *
     * @param weaponid the value for weapon.WeaponId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public void setWeaponid(Integer weaponid) {
        this.weaponid = weaponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weapon.WeaponName
     *
     * @return the value of weapon.WeaponName
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public String getWeaponname() {
        return weaponname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weapon.WeaponName
     *
     * @param weaponname the value for weapon.WeaponName
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public void setWeaponname(String weaponname) {
        this.weaponname = weaponname == null ? null : weaponname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weapon.WeaponPrice
     *
     * @return the value of weapon.WeaponPrice
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public Double getWeaponprice() {
        return weaponprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weapon.WeaponPrice
     *
     * @param weaponprice the value for weapon.WeaponPrice
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public void setWeaponprice(Double weaponprice) {
        this.weaponprice = weaponprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weapon.WeaponStore
     *
     * @return the value of weapon.WeaponStore
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public Integer getWeaponstore() {
        return weaponstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weapon.WeaponStore
     *
     * @param weaponstore the value for weapon.WeaponStore
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public void setWeaponstore(Integer weaponstore) {
        this.weaponstore = weaponstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weapon.WeaponFeatureId
     *
     * @return the value of weapon.WeaponFeatureId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public Integer getWeaponfeatureid() {
        return weaponfeatureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weapon.WeaponFeatureId
     *
     * @param weaponfeatureid the value for weapon.WeaponFeatureId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public void setWeaponfeatureid(Integer weaponfeatureid) {
        this.weaponfeatureid = weaponfeatureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weapon.WeaponQualityId
     *
     * @return the value of weapon.WeaponQualityId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public Integer getWeaponqualityid() {
        return weaponqualityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weapon.WeaponQualityId
     *
     * @param weaponqualityid the value for weapon.WeaponQualityId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public void setWeaponqualityid(Integer weaponqualityid) {
        this.weaponqualityid = weaponqualityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weapon.WeaponTypeId
     *
     * @return the value of weapon.WeaponTypeId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public Integer getWeapontypeid() {
        return weapontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weapon.WeaponTypeId
     *
     * @param weapontypeid the value for weapon.WeaponTypeId
     *
     * @mbggenerated Thu May 27 13:57:00 CST 2021
     */
    public void setWeapontypeid(Integer weapontypeid) {
        this.weapontypeid = weapontypeid;
    }
}