package com.csgo.po;

import java.io.Serializable;

public class weaponfeature implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weaponfeature.WeaponFeatureId
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    private Integer weaponfeatureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weaponfeature.WeaponFeatureName
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    private String weaponfeaturename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weaponfeature
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weaponfeature.WeaponFeatureId
     *
     * @return the value of weaponfeature.WeaponFeatureId
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    public Integer getWeaponfeatureid() {
        return weaponfeatureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weaponfeature.WeaponFeatureId
     *
     * @param weaponfeatureid the value for weaponfeature.WeaponFeatureId
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    public void setWeaponfeatureid(Integer weaponfeatureid) {
        this.weaponfeatureid = weaponfeatureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weaponfeature.WeaponFeatureName
     *
     * @return the value of weaponfeature.WeaponFeatureName
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    public String getWeaponfeaturename() {
        return weaponfeaturename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weaponfeature.WeaponFeatureName
     *
     * @param weaponfeaturename the value for weaponfeature.WeaponFeatureName
     *
     * @mbggenerated Thu May 27 15:38:42 CST 2021
     */
    public void setWeaponfeaturename(String weaponfeaturename) {
        this.weaponfeaturename = weaponfeaturename == null ? null : weaponfeaturename.trim();
    }
}