package com.csgo.po;

import java.io.Serializable;

public class Weapontype implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weapontype.WeaponTypeId
     *
     * @mbggenerated Sun May 16 23:02:32 CST 2021
     */
    private Integer weapontypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weapontype.WeaponTypeName
     *
     * @mbggenerated Sun May 16 23:02:32 CST 2021
     */
    private String weapontypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weapontype
     *
     * @mbggenerated Sun May 16 23:02:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weapontype.WeaponTypeId
     *
     * @return the value of weapontype.WeaponTypeId
     *
     * @mbggenerated Sun May 16 23:02:32 CST 2021
     */
    public Integer getWeapontypeid() {
        return weapontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weapontype.WeaponTypeId
     *
     * @param weapontypeid the value for weapontype.WeaponTypeId
     *
     * @mbggenerated Sun May 16 23:02:32 CST 2021
     */
    public void setWeapontypeid(Integer weapontypeid) {
        this.weapontypeid = weapontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weapontype.WeaponTypeName
     *
     * @return the value of weapontype.WeaponTypeName
     *
     * @mbggenerated Sun May 16 23:02:32 CST 2021
     */
    public String getWeapontypename() {
        return weapontypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weapontype.WeaponTypeName
     *
     * @param weapontypename the value for weapontype.WeaponTypeName
     *
     * @mbggenerated Sun May 16 23:02:32 CST 2021
     */
    public void setWeapontypename(String weapontypename) {
        this.weapontypename = weapontypename == null ? null : weapontypename.trim();
    }
}